post/urls.py
from django.urls import path

from .views import HomeView, PostView, PostCreateView, PostUpdateView, PostDeleteView, CommentDeleteView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('post/<pk>/<slug:slug>', PostView.as_view(), name='post'),
    path('post/create/', PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>/', PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('post/comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment_delete'),
]

project/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('post.urls', 'post'), namespace='post')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/models.py
from django.db import models
from django.conf import settings


class Post(models.Model):
    title = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title


class Comment(models.Model):
    name = models.CharField(max_length=50)
    content = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Comment by {}'.format(self.name)

post/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'content')

post/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.utils.text import slugify
from django.urls import reverse_lazy
from django.contrib import messages
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)

from .models import Post, Comment
from .forms import CommentForm


class HomeView(ListView):
    template_name = 'post/home.html'
    queryset = Post.objects.all()
    paginate_by = 2


class PostView(DetailView):
    model = Post
    template_name = "post/post.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs["pk"]
        slug = self.kwargs["slug"]

        form = CommentForm()
        post = get_object_or_404(Post, pk=pk, slug=slug)
        comments = post.comment_set.all()

        context['post'] = post
        context['comments'] = comments
        context['form'] = form
        return context

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        self.object = self.get_object()
        context = super().get_context_data(**kwargs)

        post = Post.objects.filter(id=self.kwargs['pk'])[0]
        comments = post.comment_set.all()

        context['post'] = post
        context['comments'] = comments
        context['form'] = form

        if form.is_valid():
            name = form.cleaned_data['name']
            content = form.cleaned_data['content']

            comment = Comment.objects.create(
                name=name, content=content, post=post
            )

            form = CommentForm()
            context['form'] = form
            return self.render_to_response(context=context)

        return self.render_to_response(context=context)


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ["title", "content"]

    def get_success_url(self):
        messages.success(
            self.request, 'Your post has been created successfully.')
        return reverse_lazy("post:home")

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user
        obj.slug = slugify(form.cleaned_data['title'])
        obj.save()
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ["title", "content"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        update = True
        context['update'] = update

        return context

    def get_success_url(self):
        messages.success(
            self.request, 'Your post has been updated successfully.')
        
        return reverse_lazy("post:post", kwargs={'pk': self.get_object().id, "slug" : self.get_object().slug  })

    def get_queryset(self):
        return self.model.objects.filter(author=self.request.user)


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post

    def get_success_url(self):
        messages.success(
            self.request, 'Your post has been deleted successfully.')
        return reverse_lazy("post:home")

    def get_queryset(self):
        return self.model.objects.filter(author=self.request.user)


class CommentDeleteView(LoginRequiredMixin, DeleteView):
    model = Comment

    
    def get_success_url(self):

        messages.success(
            self.request, 'Comment has been deleted successfully.')
        return reverse_lazy("post:post", kwargs={'pk': self.get_object().post.id, "slug" : self.get_object().post.slug  })

templates/post/comment_confirm_delete.html
{% extends "base.html" %} 
{% block head_title %}Delete comment {% endblock head_title %} 
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-8 offset-2">
      <h2 class="my-5">Delete comment</h2>
      <form method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete it?</p>
        <button type="submit" class="btn btn-danger">Submit</button>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

templates/post/home.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">

  <div class="row">
    {% for post in object_list %}
    <div class="card col-lg-6 offset-lg-3 mb-3">
      {% if post.image %}
      <img class="card-img-top mt-3" src="{{ post.image.url }}" alt="{{ post.title }}">
      {% endif %}
      <div class="card-body">
        <a href="{% url 'post:post' post.id post.slug %}">
          <h2 class="card-title my-3">{{ post.title }} </h2>
        </a>
        <div class="text-muted mb-3">
          <div>
            <span>Created: {{ post.created_on|date:"N j Y" }} |</span>
            <span>Updated: {{ post.updated_on|timesince }} ago |</span>

            {% if post.author %}
            <span>Posted by <a
              class="badge badge-secondary"
            >
              {{ post.author.username }}
            </a></span>
            {% else %}

            <span>Posted by <a
              class="badge badge-secondary"
            > Deleted User
            </a></span>

            {% endif %}
          </div>
          {% comment %} <div>
            <ul class="list-group">
              {% for comment in post.comment_set.all %}
            <li class="list-group-item">{{ comment.content }}</li>
            {% endfor %}
            </ul>
          </div> {% endcomment %}
        </div>
        <p class="card-text">{{ post.content|truncatewords:20 }}</p>
        <div>
          <ul class="list-group">
            {% for comment in post.comment_set.all|slice:":3" %}
          <li class="list-group-item">{{ comment.content }} by <a
            class="badge badge-secondary">
            {{ comment.name }}
          </a></li>
          {% endfor %}
          </ul>
        </div>

        <a class='btn btn-primary' style='margin-top:10px' href="{% url 'post:post' post.id post.slug %}">Read more ...</a>
      </div>
    </div>
    {% endfor %}
  </div>

  <!-- Pagination -->
  <div class="row">
    <nav class="col-lg-6 offset-lg-3 mt-4 d-flex justify-content-center">
      <ul class="pagination">

        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#"">Previous</a>
        </li>
        {% endif %}
  
        {% for i in page_obj.paginator.page_range %}
        <li class=" page-item {% if page_obj.number == i %}active{% endif %}">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#">Next</a>
        </li>
        {% endif %}

      </ul>
    </nav>
  </div>
  <!-- /Pagination -->

</div>
{% endblock %}

templates/post/post.html
{% extends 'base.html' %} {% load static %} {% block head_title %}{{ post.title
}}{% endblock %} {% block content %}
<div class="container-fluid my-5">
  <div class="row">
    <div class="col-lg-6 offset-lg-3">
      <div class="card">
        <h2 class="card-title text-center my-3">{{ post.title }}</h2>
        <div class="text-muted text-center mb-3">
          {% if post.author %}
          <div>
            Created: {{ post.created_on|date:"N j Y" }} | Updated: {{ post.updated_on|timesince }} | Posted by
            <a class="badge badge-secondary"> {{ post.author.username }} </a>
          </div>

          {% else %}

          <div>
            Created: {{ post.created_on|date:"N j Y" }} | Updated: {{
            post.updated_on|timesince }} | Posted by
            <a class="badge badge-secondary"> Deleted User </a>
          </div>

          {% endif %}

          
        </div>
       {% if post.author == request.user %}
        <div class="mt-4 mx-3">
          <a class="btn btn-primary" href="{% url 'post:post_update' post.id %}"
            >Edit</a
          >
          <a class="btn btn-danger" href="{% url 'post:post_delete' post.id %}"
            >Delete</a
          >
        </div>
        {% endif %}
        <div class="card-text mt-5 p-4">{{ post.content }}</div>
      </div>
    </div>
  </div>

  <!-- List of comments -->
  {% if comments %}
  <div class="row mt-5">
    <div class="col-lg-6 offset-lg-3">
      Comment{{ comments.count|pluralize }}
      <span class="badge badge-dark ml-2">{{ comments.count }}</span>
    </div>
    {% for comment in comments %}
    <div class="col-lg-6 offset-lg-3 mt-2">
      <div class="card p-2">
        <div class="row">
          <div class="col-12">
            <img
              class="rounded-circle mr-2"
              src="{% static 'img/avatar.svg' %}"
              alt="Avatar"
            />
            <strong>{{ comment.name }}</strong> said
          </div>
          <div class="col-12">
            <p class="m-1 mt-3">{{ comment.content }}</p>
            <p class="text-right text-muted">
              <small>{{ comment.created }}</small>
            </p>
            {% if post.author == request.user %}
            <a
              class="btn btn-danger"
              href="{% url 'post:comment_delete' comment.id %}"
              >Delete</a
            >
            {% endif %}
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% endif %}

  <!-- Form to leave comment -->
  <div class="row mt-5">
    <div class="col-lg-6 offset-lg-3">
      <h3>Leave a comment</h3>
      <form method="POST">
        {% csrf_token %}
        <div class="form-group">
          <span class="ml-2"></span>{{ form.name.label_tag }}
          <input
            type="text"
            class="form-control {% if form.name.errors %}is-invalid{% endif %}"
            id="id_name"
            name="name"
            value="{{ form.name.value|default:'' }}"
          />
        </div>

        <div class="form-group">
          <span class="ml-2"></span>{{ form.content.label_tag }}
          <textarea
            class="form-control {% if form.content.errors %}is-invalid{% endif %}"
            id="id_content"
            name="content"
            rows="4"
          >
{{ form.content.value|default:'' }}</textarea
          >
        </div>
        <button class="btn btn-primary ml-2" type="submit">Reply</button>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

templates/post/post_confirm_delete.html
{% extends "base.html" %}

{% block head_title %}Delete post{% endblock head_title %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-8 offset-2">
      <h2 class=" my-5">Delete post</h2>
      <form method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete it?</p>
        <button type="submit" class="btn btn-danger">Submit
        </button>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

templates/post/post_form.html
{% extends "base.html" %}

{% block head_title %}{% if update %}Update post{% else %}Create a post{% endif %}{% endblock head_title %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-8 offset-2">
      <h2 class=" my-5">{% if update %}Update post{% else %}Create a post{% endif %}</h2>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-group">
          {{ form.title.label_tag }}
          <input type="text" class="form-control {% if form.title.errors %}is-invalid{% endif %}" id="id_title"
            name="title" value='{{ form.title.value|default:"" }}'>
          {% if form.title.errors %}
          <div class="invalid-feedback">{{ form.title.errors }}</div>
          {% endif %}
        </div>

        <div class="form-group">
          {{ form.content.label_tag }}
          <textarea type="text" class="form-control {% if form.content.errors %}is-invalid{% endif %}" id="id_content"
            name="content" cols="40" rows="10">{{ form.content.value|default:"" }}</textarea>
          {% if form.content.errors %}
          <div class="invalid-feedback">{{ form.content.errors }}</div>
          {% endif %}
        </div>


        <button type="submit" class="btn btn-primary">
          {% if update %}Update the post{% else %}Create a post{% endif %}
        </button>
      </form>

    </div>
  </div>
</div>
{% endblock content %}